"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'Picanto';
console.log("is car == 'Picanto'? |predict False");
console.log(car == 'Picanto');
let name = 'Maryam';
console.log("is name == Emaan?");
console.log(name == 'Emaan');
let school = 'Sunrise Public School';
console.log('is school == Sadqain Grammar School?');
console.log(school == 'Sadqain Grammar School');
let color = 'Teal';
console.log("is color == Teal?");
console.log(color == 'Teal');
let university = 'Hamdard University';
console.log('is university == Harvard?');
console.log(university == 'Harvard');
let phone = 'Iphone';
console.log('is phone == Infinix?');
console.log(phone == 'infinix');
let laptop = 'Asus';
console.log('is laptop == Asus?');
console.log(laptop == 'Asus');
let dress = 'Green';
console.log('is dress == Green');
console.log(dress == 'green');
let application = 'vs code';
console.log('is application == vs code?');
console.log(application == 'vs code');
let hair = 'grey';
console.log('is hair == grey?');
console.log(hair == 'grey');
